services:
  bitwarden:
    image: vaultwarden/server
    container_name: bitwarden
    hostname: bitwarden
    volumes:
      - ./data:/data
    environment:
      WEBSOCKET_ENABLED: ${WEBSOCKET_ENABLED}
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED}
    network_mode: host
