services:
  bitwarden:
    image: vaultwarden/server
    container_name: bitwarden
    hostname: bitwarden
    volumes:
      - ${BITWARDEN_DATA_FOLDER:-./data}:/data
    environment:
      WEBSOCKET_ENABLED: ${WEBSOCKET_ENABLED}
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      DOMAIN: ${EXTERNAL_URL}
    networks:
      external:
        ipv4_address: ${BITWARDEN_IP}

networks:
  external:
    external: true
    name: ${EXTERNAL_NETWORK_NAME}